# -*- coding: utf-8 -*-
"""Retail_Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTz3i9z9a4ze538MGdmIZblli610FRHI
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the dataset

df = pd.read_csv("data.csv")   # Use this line for .csv

# Display first few rows
df.head()

# Convert 'sale_date' to datetime format
df['sale_date'] = pd.to_datetime(df['sale_date'])

# Extract month
df['Month'] = df['sale_date'].dt.to_period('M')

# Calculate Total Sales
df['Total Sales'] = df['quantiy'] * df['price_per_unit']

df.head()

import matplotlib.pyplot as plt
import seaborn as sns

monthly_sales = df.groupby('Month')['Total Sales'].sum().reset_index()
monthly_sales['Month'] = monthly_sales['Month'].astype(str)

plt.figure(figsize=(10,5))
sns.lineplot(data=monthly_sales, x='Month', y='Total Sales', marker='o')
plt.title("Monthly Sales Trend")
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

top_products = df.groupby('category')['Total Sales'].sum().nlargest(10).reset_index()

plt.figure(figsize=(10,5))
sns.barplot(data=top_products, y='category', x='Total Sales', palette='viridis')
plt.title("Top 10 Selling Products")
plt.tight_layout()
plt.show()

df.loc[:, 'age'] = df['age'].fillna(df['age'].mean())

"""### 📊 Key Insights:
- Sales peaked in December and were lowest in February.
- The most sold category was "Clothing".
- There’s an opportunity to improve sales in underperforming months.

"""